### ISSUE TITLE
Error with .tsv despite correct file name

### ISSUE THREAD

**Issue by arlenelor** [bids-standard/bids2nda#34]
Hello,

I'm currently working with a dataset that has a run that incorporates the subject name, session, task and run number (for example, the file that I'm working with is sub-01_ses-01_task-reward_run-01_bold.nii.gz). Here's the error that I get in the terminal: 

Traceback (most recent call last):
  File "/Users/Arlene1/anaconda3/bin/bids2nda", line 10, in <module>
    sys.exit(main())
  File "/Users/Arlene1/anaconda3/lib/python3.7/site-packages/bids2nda/main.py", line 418, in main
    run(args)
  File "/Users/Arlene1/anaconda3/lib/python3.7/site-packages/bids2nda/main.py", line 191, in run
    sdate = date.split("-")
UnboundLocalError: local variable 'date' referenced before assignment

I've made sure that the files in the .tsv and the actual file match and are according to BIDS specifications (such as subject, session, task  and run). Perhaps there is some type of bug?

**Comment by yarikoptic** [comment]
Looking at https://github.com/bids-standard/bids2nda/blob/master/bids2nda/main.py#L182 it seems that you lacked entry for the file in question within _scans.tsv file somewhere. Error reporting should be improved and let user know details
