### ISSUE TITLE
Image Orientation Issue

### ISSUE THREAD

**Issue by ucigrangers** [bids-standard/bids2nda#39]
Hi there, 
I am using the tool and having an issue with what looks like an inability to read in the image orientation. Is this error recognizable by anyone or due to potential lack on information in our dcm header? Thanks so much in advance, any help here would be greatly appreciated! 

Best,
Steve G.  

Traceback (most recent call last):
  File "/home/eaolson/.local/bin/bids2nda", line 8, in <module>
    sys.exit(main())
  File "/home/eaolson/.local/lib/python3.9/site-packages/bids2nda/main.py", line 421, in main
    run(args)
  File "/home/eaolson/.local/lib/python3.9/site-packages/bids2nda/main.py", line 234, in run
    dict_append(image03_dict, 'image_orientation', cosine_to_orientation(iop) if iop else '')
  File "/home/eaolson/.local/lib/python3.9/site-packages/bids2nda/main.py", line 121, in cosine_to_orientation
    raise RuntimeError(
RuntimeError: Could not deduce the image orientation of [-0.0565043, 0.861655, 0.504339, 0.00942049, 0.505583, -0.862726]. 'plane' value is array([2., 0., 0.])

**Comment by ninakougan** [comment]
@ucigrangers 

Hi Steve,
Did you ever figure out how to resolve this error?
