### ISSUE TITLE
error for a non-GUID participant

### ISSUE THREAD

**Issue by jungheejung** [bids-standard/bids2nda#41]
- I'm sharing a subset of participants in my BIDS directory.
- I have a GUIDMAPPING.txt, which as subject ids. 

```
0002 - {corresponding_GUID}
0004 - {corresponding_GUID}
0116 - {corresponding_GUID}
0118 - {corresponding_GUID}
```

- As you can see, I don't have a sub-0117. However, I get an error message for sub-0117. 
- How can I trouble shoot?

```
$ vim GUIDMAPPING.txt 
$ bids2nda ${BIDS_DIRECTORY} ${GUID_MAPPING} ${OUTPUT_DIRECTORY}
Traceback (most recent call last):
  File ".conda/envs/myenv/bin/bids2nda", line 8, in <module>
    sys.exit(main())
  File ".conda/envs/myenv/lib/python3.7/site-packages/bids2nda/main.py", line 419, in main
    run(args)
  File ".conda/envs/myenv/lib/python3.7/site-packages/bids2nda/main.py", line 172, in run
    dict_append(image03_dict, 'subjectkey', guid_mapping[bids_subject_id])
KeyError: '0117'
```

**Comment by yarikoptic** [comment]
ha -- cool to see you are trying to use it.  If you adjust your profile to switch from outdated "Boulder, Colorado" - let's see to get this fixed ;)

**Comment by jungheejung** [comment]
@yarikoptic Deal! Just fixed it.

**Comment by jcf2** [comment]
@yarikoptic I saw the same error when someone else tried to run using a table with a "not present" ID, so it seems this still needs to be addressed. What about adding an argument `--strictness` that would let you (a) skip missing IDs with a warning, (b) skip missing IDs with no warning, or (c) error out (a little more informatively than at present, though) by default?

Something like this...
```
def add_arguments(parser):
    # Existing arguments...
    parser.add_argument('--strictness', 
                        choices=['strict', 'warn', 'ignore'], 
                        default='strict',
                        help='How to handle missing subjects. '
                             'strict: raise an error, '
                             'warn: print a warning and continue, '
                             'ignore: silently skip missing subjects')
```
